// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.pax.poslink2.pigeon;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class POSLinkTest {

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class POSLinkTestApiCodec extends StandardMessageCodec {
    public static final POSLinkTestApiCodec INSTANCE = new POSLinkTestApiCodec();
    private POSLinkTestApiCodec() {}
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface POSLinkTestApi {
    void transactionStartTest(String registerReferenceNumber, Result<String> result);

    /** The codec used by POSLinkTestApi. */
    static MessageCodec<Object> getCodec() {
      return POSLinkTestApiCodec.INSTANCE;
    }

    /** Sets up an instance of `POSLinkTestApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, POSLinkTestApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.POSLinkTestApi.transactionStartTest", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String registerReferenceNumberArg = (String)args.get(0);
              if (registerReferenceNumberArg == null) {
                throw new NullPointerException("registerReferenceNumberArg unexpectedly null.");
              }
              Result<String> resultCallback = new Result<String>() {
                public void success(String result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.transactionStartTest(registerReferenceNumberArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
