// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class BatchBatchClearReq {
  BatchBatchClearReq({
    this.classID,
  });

  String? classID;

  Object encode() {
    return <Object?>[
      classID,
    ];
  }

  static BatchBatchClearReq decode(Object result) {
    result as List<Object?>;
    return BatchBatchClearReq(
      classID: result[0] as String?,
    );
  }
}

class BatchBatchCloseReq {
  BatchBatchCloseReq({
    this.classID,
  });

  String? classID;

  Object encode() {
    return <Object?>[
      classID,
    ];
  }

  static BatchBatchCloseReq decode(Object result) {
    result as List<Object?>;
    return BatchBatchCloseReq(
      classID: result[0] as String?,
    );
  }
}

class BatchBatchCloseRsp {
  BatchBatchCloseRsp({
    this.responseCode,
    this.responseMessage,
    this.hostData,
    this.totalCount,
    this.totalAmount,
    this.timeStamp,
  });

  String? responseCode;

  String? responseMessage;

  String? hostData;

  String? totalCount;

  String? totalAmount;

  String? timeStamp;

  Object encode() {
    return <Object?>[
      responseCode,
      responseMessage,
      hostData,
      totalCount,
      totalAmount,
      timeStamp,
    ];
  }

  static BatchBatchCloseRsp decode(Object result) {
    result as List<Object?>;
    return BatchBatchCloseRsp(
      responseCode: result[0] as String?,
      responseMessage: result[1] as String?,
      hostData: result[2] as String?,
      totalCount: result[3] as String?,
      totalAmount: result[4] as String?,
      timeStamp: result[5] as String?,
    );
  }
}

class BatchBatchClearRsp {
  BatchBatchClearRsp({
    this.responseCode,
    this.responseMessage,
  });

  String? responseCode;

  String? responseMessage;

  Object encode() {
    return <Object?>[
      responseCode,
      responseMessage,
    ];
  }

  static BatchBatchClearRsp decode(Object result) {
    result as List<Object?>;
    return BatchBatchClearRsp(
      responseCode: result[0] as String?,
      responseMessage: result[1] as String?,
    );
  }
}

class _POSLinkBatchApiCodec extends StandardMessageCodec {
  const _POSLinkBatchApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BatchBatchClearReq) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is BatchBatchClearRsp) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is BatchBatchCloseReq) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is BatchBatchCloseRsp) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BatchBatchClearReq.decode(readValue(buffer)!);
      case 129: 
        return BatchBatchClearRsp.decode(readValue(buffer)!);
      case 130: 
        return BatchBatchCloseReq.decode(readValue(buffer)!);
      case 131: 
        return BatchBatchCloseRsp.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class POSLinkBatchApi {
  /// Constructor for [POSLinkBatchApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  POSLinkBatchApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _POSLinkBatchApiCodec();

  Future<BatchBatchCloseRsp> batchClose(BatchBatchCloseReq arg_req) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.poslink2.POSLinkBatchApi.batchClose', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_req]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as BatchBatchCloseRsp?)!;
    }
  }

  Future<BatchBatchClearRsp> batchClear(BatchBatchClearReq arg_req) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.poslink2.POSLinkBatchApi.batchClear', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_req]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as BatchBatchClearRsp?)!;
    }
  }
}
